# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Settings.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Setting(object):
    def setupUi(self, Setting):
        Setting.setObjectName("Setting")
        Setting.setWindowModality(QtCore.Qt.NonModal)
        Setting.resize(966, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Setting.sizePolicy().hasHeightForWidth())
        Setting.setSizePolicy(sizePolicy)
        Setting.setMinimumSize(QtCore.QSize(966, 550))
        Setting.setMaximumSize(QtCore.QSize(966, 550))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        Setting.setFont(font)
        self.main_config_widget = QtWidgets.QStackedWidget(Setting)
        self.main_config_widget.setGeometry(QtCore.QRect(250, 60, 691, 481))
        self.main_config_widget.setFrameShape(QtWidgets.QFrame.Panel)
        self.main_config_widget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.main_config_widget.setObjectName("main_config_widget")
        self.page_Softwareconfig = QtWidgets.QWidget()
        self.page_Softwareconfig.setObjectName("page_Softwareconfig")
        self.pushButton_next_SoftwareConfig = QtWidgets.QPushButton(self.page_Softwareconfig)
        self.pushButton_next_SoftwareConfig.setGeometry(QtCore.QRect(570, 410, 101, 51))
        self.pushButton_next_SoftwareConfig.setObjectName("pushButton_next_SoftwareConfig")
        self.checkBox_ExistThirdParty = QtWidgets.QCheckBox(self.page_Softwareconfig)
        self.checkBox_ExistThirdParty.setGeometry(QtCore.QRect(30, 170, 111, 16))
        self.checkBox_ExistThirdParty.setObjectName("checkBox_ExistThirdParty")
        self.lineEdit_log_format = QtWidgets.QLineEdit(self.page_Softwareconfig)
        self.lineEdit_log_format.setEnabled(False)
        self.lineEdit_log_format.setGeometry(QtCore.QRect(100, 100, 311, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lineEdit_log_format.setFont(font)
        self.lineEdit_log_format.setMaxLength(100)
        self.lineEdit_log_format.setObjectName("lineEdit_log_format")
        self.label_log_format = QtWidgets.QLabel(self.page_Softwareconfig)
        self.label_log_format.setEnabled(True)
        self.label_log_format.setGeometry(QtCore.QRect(30, 100, 51, 16))
        self.label_log_format.setObjectName("label_log_format")
        self.label_log_save_path = QtWidgets.QLabel(self.page_Softwareconfig)
        self.label_log_save_path.setGeometry(QtCore.QRect(30, 140, 81, 16))
        self.label_log_save_path.setObjectName("label_log_save_path")
        self.lineEdit_log_save_path = QtWidgets.QLineEdit(self.page_Softwareconfig)
        self.lineEdit_log_save_path.setEnabled(False)
        self.lineEdit_log_save_path.setGeometry(QtCore.QRect(120, 140, 291, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lineEdit_log_save_path.setFont(font)
        self.lineEdit_log_save_path.setMaxLength(100)
        self.lineEdit_log_save_path.setObjectName("lineEdit_log_save_path")
        self.label_update_doc_name = QtWidgets.QLabel(self.page_Softwareconfig)
        self.label_update_doc_name.setGeometry(QtCore.QRect(30, 330, 81, 16))
        self.label_update_doc_name.setObjectName("label_update_doc_name")
        self.lineEdit_update_doc_name = QtWidgets.QLineEdit(self.page_Softwareconfig)
        self.lineEdit_update_doc_name.setEnabled(False)
        self.lineEdit_update_doc_name.setGeometry(QtCore.QRect(120, 330, 141, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lineEdit_update_doc_name.setFont(font)
        self.lineEdit_update_doc_name.setMaxLength(100)
        self.lineEdit_update_doc_name.setObjectName("lineEdit_update_doc_name")
        self.lineEdit_config_path = QtWidgets.QLineEdit(self.page_Softwareconfig)
        self.lineEdit_config_path.setEnabled(False)
        self.lineEdit_config_path.setGeometry(QtCore.QRect(390, 330, 113, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lineEdit_config_path.setFont(font)
        self.lineEdit_config_path.setMaxLength(100)
        self.lineEdit_config_path.setObjectName("lineEdit_config_path")
        self.label_config_path = QtWidgets.QLabel(self.page_Softwareconfig)
        self.label_config_path.setGeometry(QtCore.QRect(280, 330, 101, 20))
        self.label_config_path.setObjectName("label_config_path")
        self.layoutWidget = QtWidgets.QWidget(self.page_Softwareconfig)
        self.layoutWidget.setGeometry(QtCore.QRect(31, 30, 371, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_projectName = QtWidgets.QLabel(self.layoutWidget)
        self.label_projectName.setObjectName("label_projectName")
        self.horizontalLayout.addWidget(self.label_projectName)
        self.lineEdit_projectName = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lineEdit_projectName.setFont(font)
        self.lineEdit_projectName.setMaxLength(100)
        self.lineEdit_projectName.setObjectName("lineEdit_projectName")
        self.horizontalLayout.addWidget(self.lineEdit_projectName)
        self.label_projectVersion = QtWidgets.QLabel(self.layoutWidget)
        self.label_projectVersion.setObjectName("label_projectVersion")
        self.horizontalLayout.addWidget(self.label_projectVersion)
        self.spinBox_projectVersion = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_projectVersion.setMinimum(1)
        self.spinBox_projectVersion.setProperty("value", 1)
        self.spinBox_projectVersion.setObjectName("spinBox_projectVersion")
        self.horizontalLayout.addWidget(self.spinBox_projectVersion)
        self.layoutWidget1 = QtWidgets.QWidget(self.page_Softwareconfig)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 60, 331, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_log_days = QtWidgets.QLabel(self.layoutWidget1)
        self.label_log_days.setObjectName("label_log_days")
        self.horizontalLayout_2.addWidget(self.label_log_days)
        self.spinBox_log_days = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_log_days.setMaximumSize(QtCore.QSize(70, 35))
        self.spinBox_log_days.setMaximum(365)
        self.spinBox_log_days.setProperty("value", 30)
        self.spinBox_log_days.setObjectName("spinBox_log_days")
        self.horizontalLayout_2.addWidget(self.spinBox_log_days)
        self.label__log_levels = QtWidgets.QLabel(self.layoutWidget1)
        self.label__log_levels.setObjectName("label__log_levels")
        self.horizontalLayout_2.addWidget(self.label__log_levels)
        self.comboBox_log_levels = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_log_levels.setObjectName("comboBox_log_levels")
        self.comboBox_log_levels.addItem("")
        self.comboBox_log_levels.addItem("")
        self.comboBox_log_levels.addItem("")
        self.comboBox_log_levels.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_log_levels)
        self.main_config_widget.addWidget(self.page_Softwareconfig)
        self.page_ConnectMech = QtWidgets.QWidget()
        self.page_ConnectMech.setObjectName("page_ConnectMech")
        self.pushButton_next_ConnectMechConfig = QtWidgets.QPushButton(self.page_ConnectMech)
        self.pushButton_next_ConnectMechConfig.setGeometry(QtCore.QRect(570, 410, 101, 51))
        self.pushButton_next_ConnectMechConfig.setObjectName("pushButton_next_ConnectMechConfig")
        self.layoutWidget2 = QtWidgets.QWidget(self.page_ConnectMech)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 210, 251, 89))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_default_len_data = QtWidgets.QLabel(self.layoutWidget2)
        self.label_default_len_data.setObjectName("label_default_len_data")
        self.horizontalLayout_6.addWidget(self.label_default_len_data)
        self.lineEdit_default_len_data = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_default_len_data.setEnabled(False)
        self.lineEdit_default_len_data.setObjectName("lineEdit_default_len_data")
        self.horizontalLayout_6.addWidget(self.lineEdit_default_len_data)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_len_client_msg = QtWidgets.QLabel(self.layoutWidget2)
        self.label_len_client_msg.setObjectName("label_len_client_msg")
        self.horizontalLayout_7.addWidget(self.label_len_client_msg)
        self.spinBox_len_client_msg = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spinBox_len_client_msg.setEnabled(False)
        self.spinBox_len_client_msg.setMinimum(1)
        self.spinBox_len_client_msg.setMaximum(1000)
        self.spinBox_len_client_msg.setProperty("value", 56)
        self.spinBox_len_client_msg.setObjectName("spinBox_len_client_msg")
        self.horizontalLayout_7.addWidget(self.spinBox_len_client_msg)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_len_mech_msg = QtWidgets.QLabel(self.layoutWidget2)
        self.label_len_mech_msg.setObjectName("label_len_mech_msg")
        self.horizontalLayout_8.addWidget(self.label_len_mech_msg)
        self.spinBox_len_mech_msg = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spinBox_len_mech_msg.setEnabled(False)
        self.spinBox_len_mech_msg.setMinimum(1)
        self.spinBox_len_mech_msg.setMaximum(1000)
        self.spinBox_len_mech_msg.setProperty("value", 660)
        self.spinBox_len_mech_msg.setObjectName("spinBox_len_mech_msg")
        self.horizontalLayout_8.addWidget(self.spinBox_len_mech_msg)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.layoutWidget3 = QtWidgets.QWidget(self.page_ConnectMech)
        self.layoutWidget3.setGeometry(QtCore.QRect(21, 83, 295, 25))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_MechCenter_Port = QtWidgets.QLabel(self.layoutWidget3)
        self.label_MechCenter_Port.setObjectName("label_MechCenter_Port")
        self.horizontalLayout_5.addWidget(self.label_MechCenter_Port)
        self.lineEdit_MechCenter_Port = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_MechCenter_Port.setObjectName("lineEdit_MechCenter_Port")
        self.horizontalLayout_5.addWidget(self.lineEdit_MechCenter_Port)
        self.layoutWidget4 = QtWidgets.QWidget(self.page_ConnectMech)
        self.layoutWidget4.setGeometry(QtCore.QRect(21, 52, 294, 25))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_MechCenter_IP = QtWidgets.QLabel(self.layoutWidget4)
        self.label_MechCenter_IP.setObjectName("label_MechCenter_IP")
        self.horizontalLayout_4.addWidget(self.label_MechCenter_IP)
        self.lineEdit_MechCenter_IP = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_MechCenter_IP.setObjectName("lineEdit_MechCenter_IP")
        self.horizontalLayout_4.addWidget(self.lineEdit_MechCenter_IP)
        self.layoutWidget5 = QtWidgets.QWidget(self.page_ConnectMech)
        self.layoutWidget5.setGeometry(QtCore.QRect(21, 20, 401, 27))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(15)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_CommuniteFormat = QtWidgets.QLabel(self.layoutWidget5)
        self.label_CommuniteFormat.setObjectName("label_CommuniteFormat")
        self.horizontalLayout_3.addWidget(self.label_CommuniteFormat)
        self.comboBox_CommuniteFormat = QtWidgets.QComboBox(self.layoutWidget5)
        self.comboBox_CommuniteFormat.setObjectName("comboBox_CommuniteFormat")
        self.comboBox_CommuniteFormat.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_CommuniteFormat)
        self.comboBox_CommuniteFormat_2 = QtWidgets.QComboBox(self.layoutWidget5)
        self.comboBox_CommuniteFormat_2.setObjectName("comboBox_CommuniteFormat_2")
        self.comboBox_CommuniteFormat_2.addItem("")
        self.comboBox_CommuniteFormat_2.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_CommuniteFormat_2)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_endian = QtWidgets.QLabel(self.layoutWidget5)
        self.label_endian.setObjectName("label_endian")
        self.horizontalLayout_9.addWidget(self.label_endian)
        self.comboBox_endian = QtWidgets.QComboBox(self.layoutWidget5)
        self.comboBox_endian.setObjectName("comboBox_endian")
        self.comboBox_endian.addItem("")
        self.comboBox_endian.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_endian)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.main_config_widget.addWidget(self.page_ConnectMech)
        self.page_ConnetRobot = QtWidgets.QWidget()
        self.page_ConnetRobot.setObjectName("page_ConnetRobot")
        self.label_RobotVendor = QtWidgets.QLabel(self.page_ConnetRobot)
        self.label_RobotVendor.setGeometry(QtCore.QRect(20, 30, 101, 20))
        self.label_RobotVendor.setObjectName("label_RobotVendor")
        self.pushButton_next_ConnectRobotConfig = QtWidgets.QPushButton(self.page_ConnetRobot)
        self.pushButton_next_ConnectRobotConfig.setGeometry(QtCore.QRect(570, 410, 101, 51))
        self.pushButton_next_ConnectRobotConfig.setObjectName("pushButton_next_ConnectRobotConfig")
        self.comboBox_RobotVendor = QtWidgets.QComboBox(self.page_ConnetRobot)
        self.comboBox_RobotVendor.setGeometry(QtCore.QRect(130, 30, 81, 22))
        self.comboBox_RobotVendor.setObjectName("comboBox_RobotVendor")
        self.comboBox_RobotVendor.addItem("")
        self.comboBox_RobotVendor.addItem("")
        self.comboBox_RobotVendor.addItem("")
        self.label_RobotIP = QtWidgets.QLabel(self.page_ConnetRobot)
        self.label_RobotIP.setGeometry(QtCore.QRect(20, 70, 121, 20))
        self.label_RobotIP.setObjectName("label_RobotIP")
        self.lineEdit_RobotIP = QtWidgets.QLineEdit(self.page_ConnetRobot)
        self.lineEdit_RobotIP.setGeometry(QtCore.QRect(140, 70, 113, 20))
        self.lineEdit_RobotIP.setText("")
        self.lineEdit_RobotIP.setObjectName("lineEdit_RobotIP")
        self.label_RobotPort = QtWidgets.QLabel(self.page_ConnetRobot)
        self.label_RobotPort.setGeometry(QtCore.QRect(20, 100, 121, 20))
        self.label_RobotPort.setObjectName("label_RobotPort")
        self.lineEdit_RobotPort = QtWidgets.QLineEdit(self.page_ConnetRobot)
        self.lineEdit_RobotPort.setGeometry(QtCore.QRect(140, 100, 113, 20))
        self.lineEdit_RobotPort.setText("")
        self.lineEdit_RobotPort.setObjectName("lineEdit_RobotPort")
        self.comboBox_RobotType = QtWidgets.QComboBox(self.page_ConnetRobot)
        self.comboBox_RobotType.setGeometry(QtCore.QRect(230, 30, 81, 22))
        self.comboBox_RobotType.setObjectName("comboBox_RobotType")
        self.comboBox_RobotType.addItem("")
        self.main_config_widget.addWidget(self.page_ConnetRobot)
        self.page_ConnetThirdParty = QtWidgets.QWidget()
        self.page_ConnetThirdParty.setObjectName("page_ConnetThirdParty")
        self.pushButton_SaveConfig = QtWidgets.QPushButton(self.page_ConnetThirdParty)
        self.pushButton_SaveConfig.setGeometry(QtCore.QRect(570, 410, 101, 51))
        self.pushButton_SaveConfig.setObjectName("pushButton_SaveConfig")
        self.main_config_widget.addWidget(self.page_ConnetThirdParty)
        self.pushButton_helpDoc = QtWidgets.QPushButton(Setting)
        self.pushButton_helpDoc.setEnabled(True)
        self.pushButton_helpDoc.setGeometry(QtCore.QRect(110, 20, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_helpDoc.sizePolicy().hasHeightForWidth())
        self.pushButton_helpDoc.setSizePolicy(sizePolicy)
        self.pushButton_helpDoc.setObjectName("pushButton_helpDoc")
        self.label_tip = QtWidgets.QLabel(Setting)
        self.label_tip.setGeometry(QtCore.QRect(250, 20, 271, 16))
        self.label_tip.setObjectName("label_tip")
        self.layoutWidget6 = QtWidgets.QWidget(Setting)
        self.layoutWidget6.setGeometry(QtCore.QRect(30, 70, 161, 421))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_SoftWareConfig = QtWidgets.QPushButton(self.layoutWidget6)
        self.pushButton_SoftWareConfig.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SoftWareConfig.sizePolicy().hasHeightForWidth())
        self.pushButton_SoftWareConfig.setSizePolicy(sizePolicy)
        self.pushButton_SoftWareConfig.setObjectName("pushButton_SoftWareConfig")
        self.verticalLayout.addWidget(self.pushButton_SoftWareConfig)
        self.pushButton_ConnectMech = QtWidgets.QPushButton(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ConnectMech.sizePolicy().hasHeightForWidth())
        self.pushButton_ConnectMech.setSizePolicy(sizePolicy)
        self.pushButton_ConnectMech.setObjectName("pushButton_ConnectMech")
        self.verticalLayout.addWidget(self.pushButton_ConnectMech)
        self.pushButton_ConnectRobot = QtWidgets.QPushButton(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ConnectRobot.sizePolicy().hasHeightForWidth())
        self.pushButton_ConnectRobot.setSizePolicy(sizePolicy)
        self.pushButton_ConnectRobot.setObjectName("pushButton_ConnectRobot")
        self.verticalLayout.addWidget(self.pushButton_ConnectRobot)
        self.pushButton_ConnectThirdParty = QtWidgets.QPushButton(self.layoutWidget6)
        self.pushButton_ConnectThirdParty.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ConnectThirdParty.sizePolicy().hasHeightForWidth())
        self.pushButton_ConnectThirdParty.setSizePolicy(sizePolicy)
        self.pushButton_ConnectThirdParty.setObjectName("pushButton_ConnectThirdParty")
        self.verticalLayout.addWidget(self.pushButton_ConnectThirdParty)
        self.pushButton_ResetConfig = QtWidgets.QPushButton(Setting)
        self.pushButton_ResetConfig.setGeometry(QtCore.QRect(860, 20, 81, 31))
        self.pushButton_ResetConfig.setObjectName("pushButton_ResetConfig")

        self.retranslateUi(Setting)
        self.main_config_widget.setCurrentIndex(0)
        self.comboBox_log_levels.setCurrentIndex(1)
        self.comboBox_CommuniteFormat_2.setCurrentIndex(0)
        self.comboBox_endian.setCurrentIndex(0)
        self.comboBox_RobotVendor.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Setting)

    def retranslateUi(self, Setting):
        _translate = QtCore.QCoreApplication.translate
        Setting.setWindowTitle(_translate("Setting", "设置"))
        self.pushButton_next_SoftwareConfig.setText(_translate("Setting", "下一步"))
        self.checkBox_ExistThirdParty.setToolTip(_translate("Setting", "使用除了Mech、Robot之外的第三方设备"))
        self.checkBox_ExistThirdParty.setText(_translate("Setting", "添加第三方设备"))
        self.lineEdit_log_format.setToolTip(_translate("Setting", "日志格式"))
        self.label_log_format.setToolTip(_translate("Setting", "日志格式"))
        self.label_log_format.setText(_translate("Setting", "日志格式"))
        self.label_log_save_path.setToolTip(_translate("Setting", "日志存储路径"))
        self.label_log_save_path.setText(_translate("Setting", "日志存储路径"))
        self.lineEdit_log_save_path.setToolTip(_translate("Setting", "日志存储路径"))
        self.label_update_doc_name.setToolTip(_translate("Setting", "日志存储路径"))
        self.label_update_doc_name.setText(_translate("Setting", "版本更新文档"))
        self.lineEdit_update_doc_name.setToolTip(_translate("Setting", "日志存储路径"))
        self.lineEdit_config_path.setToolTip(_translate("Setting", "日志存储路径"))
        self.label_config_path.setToolTip(_translate("Setting", "日志存储路径"))
        self.label_config_path.setText(_translate("Setting", "配置文件存储路径"))
        self.label_projectName.setToolTip(_translate("Setting", "用于部署时区分和命名当前工程"))
        self.label_projectName.setText(_translate("Setting", "部署工程名称"))
        self.lineEdit_projectName.setToolTip(_translate("Setting", "命名不允许存在空格"))
        self.lineEdit_projectName.setText(_translate("Setting", "default_template"))
        self.label_projectVersion.setToolTip(_translate("Setting", "用于部署工程版本迭代的区分"))
        self.label_projectVersion.setText(_translate("Setting", "部署工程版本号"))
        self.spinBox_projectVersion.setToolTip(_translate("Setting", "用于部署工程版本迭代的区分"))
        self.label_log_days.setToolTip(_translate("Setting", "自动清除不在有效期的历史日志"))
        self.label_log_days.setText(_translate("Setting", "日志记录有效期"))
        self.spinBox_log_days.setToolTip(_translate("Setting", "自动清除不在有效期的历史日志"))
        self.label__log_levels.setToolTip(_translate("Setting", "仅输出高于此等级的日志信息"))
        self.label__log_levels.setText(_translate("Setting", "日志记录等级"))
        self.comboBox_log_levels.setToolTip(_translate("Setting", "仅输出高于此等级的日志信息"))
        self.comboBox_log_levels.setCurrentText(_translate("Setting", "INFO"))
        self.comboBox_log_levels.setItemText(0, _translate("Setting", "DEBUG"))
        self.comboBox_log_levels.setItemText(1, _translate("Setting", "INFO"))
        self.comboBox_log_levels.setItemText(2, _translate("Setting", "WARNING"))
        self.comboBox_log_levels.setItemText(3, _translate("Setting", "ERROR"))
        self.pushButton_next_ConnectMechConfig.setText(_translate("Setting", "下一步"))
        self.label_default_len_data.setText(_translate("Setting", "默认接收帧数据长度"))
        self.lineEdit_default_len_data.setText(_translate("Setting", "1024"))
        self.label_len_client_msg.setToolTip(_translate("Setting", "用于部署工程版本迭代的区分"))
        self.label_len_client_msg.setText(_translate("Setting", "发送信息长度(InterFace)"))
        self.spinBox_len_client_msg.setToolTip(_translate("Setting", "用于部署工程版本迭代的区分"))
        self.label_len_mech_msg.setToolTip(_translate("Setting", "用于部署工程版本迭代的区分"))
        self.label_len_mech_msg.setText(_translate("Setting", "接收信息长度(InterFace)"))
        self.spinBox_len_mech_msg.setToolTip(_translate("Setting", "用于部署工程版本迭代的区分"))
        self.label_MechCenter_Port.setText(_translate("Setting", "Mech-InterFace接口 端口号"))
        self.lineEdit_MechCenter_Port.setText(_translate("Setting", "50000"))
        self.label_MechCenter_IP.setText(_translate("Setting", "Mech-InterFace接口 IP地址"))
        self.lineEdit_MechCenter_IP.setText(_translate("Setting", "127.0.0.1"))
        self.label_CommuniteFormat.setText(_translate("Setting", "通讯格式"))
        self.comboBox_CommuniteFormat.setItemText(0, _translate("Setting", "Mech标准接口(InterFace)"))
        self.comboBox_CommuniteFormat_2.setItemText(0, _translate("Setting", "ASCII"))
        self.comboBox_CommuniteFormat_2.setItemText(1, _translate("Setting", "HEX"))
        self.label_endian.setText(_translate("Setting", "端方向"))
        self.comboBox_endian.setItemText(0, _translate("Setting", "<"))
        self.comboBox_endian.setItemText(1, _translate("Setting", ">"))
        self.label_RobotVendor.setText(_translate("Setting", "机器人型号"))
        self.pushButton_next_ConnectRobotConfig.setText(_translate("Setting", "下一步"))
        self.comboBox_RobotVendor.setItemText(0, _translate("Setting", "ABB"))
        self.comboBox_RobotVendor.setItemText(1, _translate("Setting", "FANUC"))
        self.comboBox_RobotVendor.setItemText(2, _translate("Setting", "UR"))
        self.label_RobotIP.setText(_translate("Setting", "机器人接口 IP地址"))
        self.label_RobotPort.setText(_translate("Setting", "机器人接口 端口号"))
        self.comboBox_RobotType.setItemText(0, _translate("Setting", "UR_5"))
        self.pushButton_SaveConfig.setText(_translate("Setting", "保存配置表"))
        self.pushButton_helpDoc.setText(_translate("Setting", "说明手册"))
        self.label_tip.setText(_translate("Setting", "提示：可光标放到组件上来查看对应的详细描述"))
        self.pushButton_SoftWareConfig.setText(_translate("Setting", "1、软件设置"))
        self.pushButton_ConnectMech.setText(_translate("Setting", "2、与Mech通信设置"))
        self.pushButton_ConnectRobot.setText(_translate("Setting", "3、与Robot通信设置"))
        self.pushButton_ConnectThirdParty.setText(_translate("Setting", "4、与第三方设备通信"))
        self.pushButton_ResetConfig.setText(_translate("Setting", "重置配置表"))
