# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Settings.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Setting(object):
    def setupUi(self, Setting):
        Setting.setObjectName("Setting")
        Setting.setWindowModality(QtCore.Qt.NonModal)
        Setting.resize(966, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Setting.sizePolicy().hasHeightForWidth())
        Setting.setSizePolicy(sizePolicy)
        Setting.setMinimumSize(QtCore.QSize(966, 550))
        Setting.setMaximumSize(QtCore.QSize(966, 550))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        Setting.setFont(font)
        self.main_config_widget = QtWidgets.QStackedWidget(Setting)
        self.main_config_widget.setGeometry(QtCore.QRect(250, 60, 691, 481))
        self.main_config_widget.setFrameShape(QtWidgets.QFrame.Panel)
        self.main_config_widget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.main_config_widget.setObjectName("main_config_widget")
        self.page_Softwareconfig = QtWidgets.QWidget()
        self.page_Softwareconfig.setObjectName("page_Softwareconfig")
        self.label_projectName = QtWidgets.QLabel(self.page_Softwareconfig)
        self.label_projectName.setGeometry(QtCore.QRect(30, 30, 81, 16))
        self.label_projectName.setObjectName("label_projectName")
        self.label_projectVersion = QtWidgets.QLabel(self.page_Softwareconfig)
        self.label_projectVersion.setGeometry(QtCore.QRect(30, 60, 91, 16))
        self.label_projectVersion.setObjectName("label_projectVersion")
        self.lineEdit_projectName = QtWidgets.QLineEdit(self.page_Softwareconfig)
        self.lineEdit_projectName.setGeometry(QtCore.QRect(120, 30, 113, 20))
        self.lineEdit_projectName.setObjectName("lineEdit_projectName")
        self.lineEdit_projectVersion = QtWidgets.QLineEdit(self.page_Softwareconfig)
        self.lineEdit_projectVersion.setGeometry(QtCore.QRect(120, 60, 113, 20))
        self.lineEdit_projectVersion.setObjectName("lineEdit_projectVersion")
        self.pushButton_next_SoftwareConfig = QtWidgets.QPushButton(self.page_Softwareconfig)
        self.pushButton_next_SoftwareConfig.setGeometry(QtCore.QRect(570, 410, 101, 51))
        self.pushButton_next_SoftwareConfig.setObjectName("pushButton_next_SoftwareConfig")
        self.checkBox_ExistThirdParty = QtWidgets.QCheckBox(self.page_Softwareconfig)
        self.checkBox_ExistThirdParty.setGeometry(QtCore.QRect(30, 100, 111, 16))
        self.checkBox_ExistThirdParty.setObjectName("checkBox_ExistThirdParty")
        self.main_config_widget.addWidget(self.page_Softwareconfig)
        self.page_ConnectMech = QtWidgets.QWidget()
        self.page_ConnectMech.setObjectName("page_ConnectMech")
        self.lineEdit_MechCenter_Port = QtWidgets.QLineEdit(self.page_ConnectMech)
        self.lineEdit_MechCenter_Port.setGeometry(QtCore.QRect(190, 80, 113, 20))
        self.lineEdit_MechCenter_Port.setObjectName("lineEdit_MechCenter_Port")
        self.label_MechCenter_Port = QtWidgets.QLabel(self.page_ConnectMech)
        self.label_MechCenter_Port.setGeometry(QtCore.QRect(20, 80, 161, 20))
        self.label_MechCenter_Port.setObjectName("label_MechCenter_Port")
        self.lineEdit_MechCenter_IP = QtWidgets.QLineEdit(self.page_ConnectMech)
        self.lineEdit_MechCenter_IP.setGeometry(QtCore.QRect(190, 50, 113, 20))
        self.lineEdit_MechCenter_IP.setObjectName("lineEdit_MechCenter_IP")
        self.label_MechCenter_IP = QtWidgets.QLabel(self.page_ConnectMech)
        self.label_MechCenter_IP.setGeometry(QtCore.QRect(20, 50, 161, 20))
        self.label_MechCenter_IP.setObjectName("label_MechCenter_IP")
        self.label_CommuniteFormat = QtWidgets.QLabel(self.page_ConnectMech)
        self.label_CommuniteFormat.setGeometry(QtCore.QRect(20, 20, 51, 20))
        self.label_CommuniteFormat.setObjectName("label_CommuniteFormat")
        self.comboBox_CommuniteFormat = QtWidgets.QComboBox(self.page_ConnectMech)
        self.comboBox_CommuniteFormat.setGeometry(QtCore.QRect(120, 20, 181, 22))
        self.comboBox_CommuniteFormat.setObjectName("comboBox_CommuniteFormat")
        self.comboBox_CommuniteFormat.addItem("")
        self.comboBox_CommuniteFormat_2 = QtWidgets.QComboBox(self.page_ConnectMech)
        self.comboBox_CommuniteFormat_2.setGeometry(QtCore.QRect(310, 20, 61, 22))
        self.comboBox_CommuniteFormat_2.setObjectName("comboBox_CommuniteFormat_2")
        self.comboBox_CommuniteFormat_2.addItem("")
        self.comboBox_CommuniteFormat_2.addItem("")
        self.pushButton_next_ConnectMechConfig = QtWidgets.QPushButton(self.page_ConnectMech)
        self.pushButton_next_ConnectMechConfig.setGeometry(QtCore.QRect(570, 410, 101, 51))
        self.pushButton_next_ConnectMechConfig.setObjectName("pushButton_next_ConnectMechConfig")
        self.main_config_widget.addWidget(self.page_ConnectMech)
        self.page_ConnetRobot = QtWidgets.QWidget()
        self.page_ConnetRobot.setObjectName("page_ConnetRobot")
        self.label_RobotVendor = QtWidgets.QLabel(self.page_ConnetRobot)
        self.label_RobotVendor.setGeometry(QtCore.QRect(20, 30, 101, 20))
        self.label_RobotVendor.setObjectName("label_RobotVendor")
        self.pushButton_next_ConnectRobotConfig = QtWidgets.QPushButton(self.page_ConnetRobot)
        self.pushButton_next_ConnectRobotConfig.setGeometry(QtCore.QRect(570, 410, 101, 51))
        self.pushButton_next_ConnectRobotConfig.setObjectName("pushButton_next_ConnectRobotConfig")
        self.comboBox_RobotVendor = QtWidgets.QComboBox(self.page_ConnetRobot)
        self.comboBox_RobotVendor.setGeometry(QtCore.QRect(130, 30, 81, 22))
        self.comboBox_RobotVendor.setObjectName("comboBox_RobotVendor")
        self.comboBox_RobotVendor.addItem("")
        self.comboBox_RobotVendor.addItem("")
        self.label_RobotIP = QtWidgets.QLabel(self.page_ConnetRobot)
        self.label_RobotIP.setGeometry(QtCore.QRect(20, 70, 121, 20))
        self.label_RobotIP.setObjectName("label_RobotIP")
        self.lineEdit_RobotIP = QtWidgets.QLineEdit(self.page_ConnetRobot)
        self.lineEdit_RobotIP.setGeometry(QtCore.QRect(140, 70, 113, 20))
        self.lineEdit_RobotIP.setText("")
        self.lineEdit_RobotIP.setObjectName("lineEdit_RobotIP")
        self.label_RobotPort = QtWidgets.QLabel(self.page_ConnetRobot)
        self.label_RobotPort.setGeometry(QtCore.QRect(20, 100, 121, 20))
        self.label_RobotPort.setObjectName("label_RobotPort")
        self.lineEdit_RobotPort = QtWidgets.QLineEdit(self.page_ConnetRobot)
        self.lineEdit_RobotPort.setGeometry(QtCore.QRect(140, 100, 113, 20))
        self.lineEdit_RobotPort.setText("")
        self.lineEdit_RobotPort.setObjectName("lineEdit_RobotPort")
        self.main_config_widget.addWidget(self.page_ConnetRobot)
        self.page_ConnetThirdParty = QtWidgets.QWidget()
        self.page_ConnetThirdParty.setObjectName("page_ConnetThirdParty")
        self.pushButton_SaveConfig = QtWidgets.QPushButton(self.page_ConnetThirdParty)
        self.pushButton_SaveConfig.setGeometry(QtCore.QRect(570, 410, 101, 51))
        self.pushButton_SaveConfig.setObjectName("pushButton_SaveConfig")
        self.main_config_widget.addWidget(self.page_ConnetThirdParty)
        self.pushButton_helpDoc = QtWidgets.QPushButton(Setting)
        self.pushButton_helpDoc.setEnabled(True)
        self.pushButton_helpDoc.setGeometry(QtCore.QRect(110, 20, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_helpDoc.sizePolicy().hasHeightForWidth())
        self.pushButton_helpDoc.setSizePolicy(sizePolicy)
        self.pushButton_helpDoc.setObjectName("pushButton_helpDoc")
        self.label_tip = QtWidgets.QLabel(Setting)
        self.label_tip.setGeometry(QtCore.QRect(250, 20, 271, 16))
        self.label_tip.setObjectName("label_tip")
        self.layoutWidget = QtWidgets.QWidget(Setting)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 70, 161, 421))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_SoftWareConfig = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_SoftWareConfig.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SoftWareConfig.sizePolicy().hasHeightForWidth())
        self.pushButton_SoftWareConfig.setSizePolicy(sizePolicy)
        self.pushButton_SoftWareConfig.setObjectName("pushButton_SoftWareConfig")
        self.verticalLayout.addWidget(self.pushButton_SoftWareConfig)
        self.pushButton_ConnectMech = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ConnectMech.sizePolicy().hasHeightForWidth())
        self.pushButton_ConnectMech.setSizePolicy(sizePolicy)
        self.pushButton_ConnectMech.setObjectName("pushButton_ConnectMech")
        self.verticalLayout.addWidget(self.pushButton_ConnectMech)
        self.pushButton_ConnectRobot = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ConnectRobot.sizePolicy().hasHeightForWidth())
        self.pushButton_ConnectRobot.setSizePolicy(sizePolicy)
        self.pushButton_ConnectRobot.setObjectName("pushButton_ConnectRobot")
        self.verticalLayout.addWidget(self.pushButton_ConnectRobot)
        self.pushButton_ConnectThirdParty = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_ConnectThirdParty.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ConnectThirdParty.sizePolicy().hasHeightForWidth())
        self.pushButton_ConnectThirdParty.setSizePolicy(sizePolicy)
        self.pushButton_ConnectThirdParty.setObjectName("pushButton_ConnectThirdParty")
        self.verticalLayout.addWidget(self.pushButton_ConnectThirdParty)
        self.pushButton_ResetConfig = QtWidgets.QPushButton(Setting)
        self.pushButton_ResetConfig.setGeometry(QtCore.QRect(860, 20, 81, 31))
        self.pushButton_ResetConfig.setObjectName("pushButton_ResetConfig")

        self.retranslateUi(Setting)
        self.main_config_widget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Setting)

    def retranslateUi(self, Setting):
        _translate = QtCore.QCoreApplication.translate
        Setting.setWindowTitle(_translate("Setting", "设置"))
        self.label_projectName.setText(_translate("Setting", "部署工程名称"))
        self.label_projectVersion.setText(_translate("Setting", "部署工程版本号"))
        self.pushButton_next_SoftwareConfig.setText(_translate("Setting", "下一步"))
        self.checkBox_ExistThirdParty.setText(_translate("Setting", "添加第三方设备"))
        self.label_MechCenter_Port.setText(_translate("Setting", "Mech-InterFace接口 端口号"))
        self.label_MechCenter_IP.setText(_translate("Setting", "Mech-InterFace接口 IP地址"))
        self.label_CommuniteFormat.setText(_translate("Setting", "通讯格式"))
        self.comboBox_CommuniteFormat.setItemText(0, _translate("Setting", "Mech标准接口(InterFace)"))
        self.comboBox_CommuniteFormat_2.setItemText(0, _translate("Setting", "ASCII"))
        self.comboBox_CommuniteFormat_2.setItemText(1, _translate("Setting", "HEX"))
        self.pushButton_next_ConnectMechConfig.setText(_translate("Setting", "下一步"))
        self.label_RobotVendor.setText(_translate("Setting", "机器人型号"))
        self.pushButton_next_ConnectRobotConfig.setText(_translate("Setting", "下一步"))
        self.comboBox_RobotVendor.setItemText(0, _translate("Setting", "ABB"))
        self.comboBox_RobotVendor.setItemText(1, _translate("Setting", "FANUC"))
        self.label_RobotIP.setText(_translate("Setting", "机器人接口 IP地址"))
        self.label_RobotPort.setText(_translate("Setting", "机器人接口 端口号"))
        self.pushButton_SaveConfig.setText(_translate("Setting", "保存配置"))
        self.pushButton_helpDoc.setText(_translate("Setting", "说明手册"))
        self.label_tip.setText(_translate("Setting", "提示：可光标放到组件上来查看对应的详细描述"))
        self.pushButton_SoftWareConfig.setText(_translate("Setting", "1、软件设置"))
        self.pushButton_ConnectMech.setText(_translate("Setting", "2、与Mech通信设置"))
        self.pushButton_ConnectRobot.setText(_translate("Setting", "3、与Robot通信设置"))
        self.pushButton_ConnectThirdParty.setText(_translate("Setting", "4、与第三方设备通信"))
        self.pushButton_ResetConfig.setText(_translate("Setting", "重置配置"))
