# 软件配置
software = "software"
software_name = "software_name"
software_version = "software_version"
project_name = "project_name"
project_version = "project_version"
config_path = "config_path"
third_party_equipment = "third_party_equipment"

# Mech通讯配置
mech_communication = "mech_communication"
mech_interface_ip = "mech_interface_ip"
mech_interface_port = "mech_interface_port"
communite_format = "communite_format"
is_ascii = "is_ascii"
endian = "endian"
len_client_msg = "len_client_msg"
len_mech_msg = "len_mech_msg"
default_len_data = "default_len_data"

# 机器人通讯配置
robot_communication = "robot_communication"
robot_server_agent_ip = "robot_server_agent_ip"
robot_server_agent_port = "robot_server_agent_port"
robot_vendor = "robot_vendor"
robot_type = "robot_type"


# 日志配置
log = "log"
log_save_path = "log_save_path"
log_save_level = "log_save_level"
log_back_count = "log_back_count"
log_format = "log_format"

# 展示性配置
display = "display"

# 其他设置配置
other = "other"
update_doc_name = "update_doc_name"
pwd = "pwd"
user_type = "user_type"


HeartbeatMsg = b"Heartbeat"
CheckCodeMsg = b"#CONNECT"
CloseMsg = b'#CLOSE'
FormatErrorMsg = None
LostConnectMsg = b''

######################################### 尚未启用 #################
# background_program = "background_program"
# adapter = "adapter"
# auto_start = "auto_start"
# is_simulate = "is_simulate"
# robserver_file = "robserver_file"
# is_robot_server_needed = "is_robot_server_needed"
# viz_file = "viz_file"
# viz_project = "viz_project"
# viz_speed = "viz_speed"
# is_viz_needed = "is_viz_needed"
# vision_file = "vision_file"
# vision_projects = "vision_projects"
# is_vision_needed = "is_vision_needed"
# adapter_name = "adapter_name"
# is_interface_needed = "is_interface_needed"
# is_enable_interface = "is_enable_interface"
# auto_start_external_service = "auto_start_external_service"
# eye_file = "eye_file"
# hmi_file = "hmi_file"
# backup_setting = "backup_setting"
# login_setting = "login_setting"
# backup_path = "backup_path"
# backup_options = "backup_options"
# package_path = "package_path"
# start_time = "start_time"
# end_time = "end_time"
# package_options = "package_options"
# projects = "projects"
# adapter_projects = "adapter_projects"
# deploy_settings = "deploy_settings"
# logs = "logs"
# pwd = "pwd"
# user_type = "user_type"
# start_programs_to_sys_tray = "start_programs_to_sys_tray"
# host_address = "host_address"
# interface = "interface"
# db_value = "db_value"
# interface_name = "interface_name"
# interface_format = "interface_format"
# max_log_count = "max_log_count"
# max_file_size = "max_file_size"
# log_level = "log_level"
# autolock_time = "autolock_time"
# is_hide_console = "is_hide_console"
# run_at_startup = "run_at_startup"
#
# is_dark_theme = "is_dark_theme"
# minimize_to_sys_tray = "minimize_to_sys_tray"
#
# mainwindow = "mainwindow"
# show_operation_button = "show_operation_button"
# show_message_table = "show_message_table"
# language = "language"
#
# appearance = "appearance"
#
# robot_server = "robot_server"
# robot_params_path = "robot_params_path"
# robot_vendor = "robot_vendor"
# dh_d1 = "dh_d1"
#
# network = "network"
# vision = "vision"
# viz = "viz"
# data_format = "data_format"
# robot = "robot"
# model = "model"
#
# is_server = "is_server"
# steps = "steps"
# step_name = "step_name"
# command = "command"
# is_ASCII = "is_ASCII"
# endian = "endian"
# is_bind_port = "is_bind_port"
#
# data_received = "data_received"
# data_sent = "data_sent"
# field_num = "field_num"
# photo_command = "photo_command"
# field_separator = "field_separator"
# subfield_separator = "subfield_separator"
# is_need_subfield_separator_received = "is_need_subfield_separator_received"
# is_need_subfield_separator_sent = "is_need_subfield_separator_sent"
# subfield_received_start_pos = "subfield_received_start_pos"
# subfield_received_end_pos = "subfield_received_end_pos"
# subfield_sent_start_pos = "subfield_sent_start_pos"
# subfield_sent_end_pos = "subfield_sent_end_pos"
# hex_fields = "hex_fields"
# field_data_type = "field_data_type"
# field_desc = "field_desc"
# status_codes = "status_codes"
# labels = "labels"
# label_codes = "label_codes"
# is_need_check_cloud = "is_need_check_cloud"
# is_need_send_object_label = "is_need_send_object_label"
# is_need_send_pose_num = "is_need_send_pose_num"
# is_need_fixed_body = "is_need_fixed_body"
# fixed_body = "fixed_body"
# is_need_fixed_cmd_tail = "is_need_fixed_cmd_tail"
# fixed_cmd_tail = "fixed_cmd_tail"
# status_code_data_type = "status_code_data_type"
# pose_num_data_type = "pose_num_data_type"
# pose_data_type = "pose_data_type"
# is_multi_vision_project = "is_multi_vision_project"
# vision_name_list = "vision_name_list"
# vision_name_code_list = "vision_name_code_list"
# vision_name_pos = "vision_name_pos"
# is_need_switch_model = "is_need_switch_model"
# model_type_pos = "model_type_pos"
#
# vision_name = "vision_name"
# pose_count = "pose_count"
# fixed_pose_count = "fixed_pose_count"
# is_quaternion = "is_quaternion"
# euler_type = "euler_type"
# robot_type = "robot_type"
# length_unit = "length_unit"
# angle_unit = "angle_unit"
# is_eye_to_hand = "is_eye_to_hand"
# pose_coordinate = "pose_coordinate"
# precision = "precision"
# is_use_viz_check_collision = "is_use_viz_check_collision"
#
# is_distinguish_pick_place = "is_distinguish_pick_place"
# num_of_pick_pose_in_viz = "num_of_pick_pose_in_viz"
# num_of_place_pose_in_viz = "num_of_place_pose_in_viz"
# is_need_send_num_of_pick_place = "is_need_send_num_of_pick_place"
# is_need_send_motion_type = "is_need_send_motion_type"
# motion_type_codes = "motion_type_codes"
# jps_angle_units_of_send = "jps_angle_units_of_send"
# tcp_pose_length_units_of_send = "tcp_pose_length_units_of_send"
# is_quaternion_of_send = "is_quaternion_of_send"
# tcp_pose_angle_units_of_send = "tcp_pose_angle_units_of_send"
# home_jps_for_viz = "home_jps_for_viz"
#
# is_need_setj = "is_need_setj"
# is_jps = "is_jps"
# jps_start_pos = "jps_start_pos"
# jps_end_pos = "jps_end_pos"
# robot_name = "robot_name"
# robot_dof = "robot_dof"
# jps_angle_unit = "jps_angle_unit"
# pose_angle_unit = "pose_angle_unit"
#
# model_dir = "model_dir"
# is_need_type_code = "is_need_type_code"
# is_switch_model_in_ui = "is_switch_model_in_ui"
# model_type_list = "model_type_list"
# model_type_code_list = "model_type_code_list"
# step_name_dict = "step_name_dict"
#
# # For init params in External Service
# init_point_type = "init_point_type"
# init_is_labels_needed = "init_is_labels_needed"
# init_robot_name = "init_robot_name"
# init_dof = "init_dof"
# init_dh = "init_dh"
# init_euler_type = "init_euler_type"
# init_endian_type = "init_endian_type"
# init_is_need_fixed_recv_size = "init_is_need_fixed_recv_size"
#
# # For robot server
# service_name = "name"
# service_type = "type"
# ip = "ip"
# port = "port"
# value = "value"
# simulate = "simulate"
# status = "status"
# pose = "pose"
# other_info = "other_info"
# robot_type = "robot_type"
# is_known_robot = "is_known_robot"
# custom_euler = "custom_euler"
#
# # app name
# mech_viz = "Mech-Viz"
# mech_vision = "Mech-Vision"
# mech_eye_viewer = "Mech-Eye Viewer"
# mech_center = "Mech-Center"
#
# # service keys
# project_dir = "project_dir"
# other_info = "other_info"
# camera_ip = "camera_ip"
# to_lock = "to_lock"
# backup_dir = "backup_dir"
# version = "version"
# is_ready = "is_ready"
# error_msg = "error_msg"
# exit_info = "exit_info"
# total_exec_time = "total_exec_time"
# exit_code = "exitCode"

