# Commands
# 存储指令代码
# Mech-Vision
RUN_VISION = 101
GET_VISION_DATA = 102
SWITCH_MODEL = 103

# Mech-Viz
RUN_VIZ = 201
STOP_VIZ = 202
SET_BRANCH = 203
SET_INDEX = 204
GET_VIZ_DATA = 205
GET_DO_LIST = 206 # DO list in sucker for multi pick

# Dynamic modify data
SET_BOX_SIZE = 501
SET_OUTER_POSE = 502

# Custom message
CUSTOM_MESSAGE = 601

GET_CALIBRATION_DATA = 701

GET_STATUSES = 901

valid_commands = (RUN_VISION,
                  GET_VISION_DATA,
                  SWITCH_MODEL,
                  RUN_VIZ,
                  STOP_VIZ,
                  SET_BRANCH,
                  SET_INDEX,
                  GET_VIZ_DATA,
                  GET_DO_LIST,
                  SET_BOX_SIZE,
                  SET_OUTER_POSE,
                  GET_CALIBRATION_DATA,
                  GET_STATUSES)


POINT_TYPE_NONE = 0
POINT_TYPE_JPS = 1
POINT_TYPE_POSE = 2

FIRST_CALIBRATION_REQUEST = 0
REACHED_POINT_SUCCESS = 1
REACHED_POINT_FAIL = 2

NEED_ALL_POSES = 0
MAX_POSE_COUNT_PER_TRANSMISSION = 20

SEND_NOT_COMPLETE = 0
SEND_COMPLETE = 1

DO_LIST_COUNT = 64

CALIBRATION_NOT_FINISHED = 0
CALIBRATION_FINISHED = 1

# PLC offset
# Read
OFFSET_CMD_TRIGGER = 0
OFFSET_COMMAND = 2
OFFSET_POINT_TYPE = 4
OFFSET_POSE_COUNT_REQ = 6
OFFSET_PROJECT_NUM = 8
OFFSET_MODEL_NUM = 10
OFFSET_JPS = 12
OFFSET_POSE = 36
OFFSET_BRANCH_NAME = 60
OFFSET_BRANCH_OUTPORT = 62
OFFSET_INDEX_NAME = 64
OFFSET_INDEX_ORDER = 66
OFFSET_BOX_SIZE = 68
OFFSET_OUTER_POSE = 80

# Write
OFFSET_HEARTBEAT = 198
OFFSET_STATUS_CODE = 200
OFFSET_SEND_POSE_STATUS = 202
OFFSET_SEND_POSE_COUNT = 204
OFFSET_VISUAL_MOVE_POSITION = 206
OFFSET_SEND_POSE = 208
OFFSET_SEND_LABEL = 1168
OFFSET_SEND_SPEED = 1248
OFFSET_DO_LIST = 1328


HEARTBEAT_TIME = 1
